### ISSUE TITLE
Failure to save data after server reboot

### ISSUE THREAD

**Issue by energooooo** [ConfusedAlex/GoldEconomy#41] opened 2024-09-15 15:50 UTC
If you get any coins somehow and the server restarts, all player data will be reset.
Saving to a file does not go at all. Everything is stored in the cache

Verison plugin: TheGoldEconomy-1.6.5
Version core: git-Pufferfish-28 (MC: 1.20.2)

Log spam: 
`[15:59:53] [Craft Scheduler Thread - 9722 - Towny/ERROR]: [TheGoldEconomy] Nag author(s) [ConfusedAlex] of TheGoldEconomy-1.6.4 about their async inventory modification at confusedalex.thegoldeconomy.Converter.give(Converter.java:154)
[15:59:53] [Craft Scheduler Thread - 9722 - Towny/ERROR]: [MechanicsCore] Found a bad plugin 'TheGoldEconomy' for modifying inventory async.
[15:59:53] [Craft Scheduler Thread - 9722 - Towny/ERROR]: [TheGoldEconomy] Nag author(s) [ConfusedAlex] of TheGoldEconomy-1.6.4 about their async inventory modification at confusedalex.thegoldeconomy.Converter.give(Converter.java:166)
[15:59:53] [Craft Scheduler Thread - 9722 - Towny/ERROR]: [MechanicsCore] Found a bad plugin 'TheGoldEconomy' for modifying inventory async.`

**Comment by ConfusedAlex** [comment] 2024-09-15 16:49
I cannot reproduce the issue. I tested with the Pufferfish version, but saving on leave and saving on server restart worked. Did the server crash? Is there anything other in the logs?

**Comment by energooooo** [comment] 2024-09-16 17:49
> I cannot reproduce the issue. I tested with the Pufferfish version, but saving on leave and saving on server restart worked. Did the server crash? Is there anything other in the logs?

There's nothing else in the logs. Towny 0.99.0.0 is additionally installed on the server.
Data reset happens absolutely always after a reboot with a chance of 100%

**Comment by ConfusedAlex** [comment] 2024-09-17 05:42
Mhh weird. I tested on Towny with pufferfish-28 and cannot reproduce the issue. Maybe it is another plugin, that is not working right?

**Comment by energooooo** [comment] 2024-09-17 09:11
Do you have this particular version of Towny?

**Comment by ConfusedAlex** [comment] 2024-09-18 07:12
> Do you have this particular version of Towny?

Yes, I tried with this version and MechanicsCore installed. Work's perfectly fine

**Comment by energooooo** [comment] 2024-09-19 10:39
> > Do you have this particular version of Towny?
> 
> Yes, I tried with this version and MechanicsCore installed. Work's perfectly fine

I found the cause of the data reset.
If town_prefix is not specified as default “town-” in the Towny configuration, the information will not be saved.

In my case town20- was specified and the data was not saved.

**Comment by ConfusedAlex** [comment] 2024-09-24 06:36
This is weird. There is nothing in the code that requires the prefix to be "towny". I couldn't find a upstream in Vault or Towny. Will close this issue for now, feel free to reopen

**Closed by ConfusedAlex** 2024-09-24 06:36 UTC
